# file: discord-bot-outro/kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outrobot-deployment
  namespace: discord-bots
spec:
  selector:
    matchLabels:
      app: outrobot
  replicas: 1
  template:
    metadata:
      labels:
        app: outrobot
    spec:
      containers:
      - name: outrobot
        image: gbt55/discord-bot-outro:v1.1
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: discord-outrobot
              key: api-key
            # create this secret like this: kubectl create secret generic discord-outrobot --from-literal=api-key='<yourApiKey>'



          #value: "yourApiKey"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 15
        #   periodSeconds: 20

